# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       python: 3.11
#     commands:
#       - cd Codebuild
#       - echo "Installing packages...."
#       - pip install -r requirements.txt -t library
#   build:
#     commands:
#       - echo "Zip the lambda package...."
#       - cd library
#       - zip -r9 ../lambda_package.zip .
#       - cd ..
#       - zip -g lambda_package.zip lambda_function.py
#   post_build:
#     commands:
#       - echo "Updating the lambda function...."
#       - aws lambda update-function-code --function-name pandas-function --zip-file fileb://lambda_package.zip
#       - echo "COMPLETED"

version: 0.2

phases:
  pre_build:
    commands:
      - echo "Retrieving ECR authentication token..."
      - ECR_TOKEN=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - echo "Logging in to Amazon ECR..."
      - echo $ECR_TOKEN | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - cd Codebuild
      - docker build -t modeltraining .
  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag modeltraining:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/modeltraining:latest
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/modeltraining:latest
      - echo Docker image pushed successfully
