version: 0.2

phases:
  pre_build:
    commands:
      - echo "Retrieving ECR authentication token..."
      - ECR_TOKEN=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - echo "Logging in to Amazon ECR..."
      - echo $ECR_TOKEN | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - cd Codebuild
      - docker build -t modeltraining .
  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag modeltraining:v1.0 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/modeltraining:v1.0
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/modeltraining:v1.0
      - echo Docker image pushed successfully
      # - echo Updating the Lambda function with the new Docker image...
      # - aws lambda update-function-code --function-name $FUNCTION_NAME --image-uri $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/modeltraining:v2.0
      # - echo Lambda function updated successfully
