# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       python: 3.11
#     commands:
#       - cd Codebuild
#       - echo "Installing packages...."
#       - pip install -r requirements.txt -t library
#   build:
#     commands:
#       - echo "Zip the lambda package...."
#       - cd library
#       - zip -r9 ../lambda_package.zip .
#       - cd ..
#       - zip -g lambda_package.zip lambda_function.py
#   post_build:
#     commands:
#       - echo "Updating the lambda function...."
#       - aws lambda update-function-code --function-name pandas-function --zip-file fileb://lambda_package.zip
#       - echo "COMPLETED"

version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t lambda-function .
  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag lambda-function:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/lambda-function:latest
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/lambda-function:latest
      - echo Docker image pushed successfully
